In [2]:
import numpy as np
def train_test_split(data,p): #60% train 40 % test
    split_index = int(data.shape[0]*p)

    train=data[:split_index, :]  # from zero till end
    test =data[split_index : , :] # from 12 till end

    #train

    x_train= train[:, :-1]
    y_train= train[:,-1]

    #test

    x_test= test[:, :-1]
    y_test= test[:,-1]

    return x_train, x_test, y_train, y_test



np.random.seed(12)
data = np.random.randint(1 , 10 , (20,5))
p= 0.6
x_train, x_test, y_train, y_test = train_test_split(data, p)

print("x_train:")
print(x_train)
print("\nx_test:")
print(x_test)
print("\ny_train:")
print(y_train)
print("\ny_test:")
print(y_test)








x_train:
[[7 2 3 4]
 [1 7 2 5]
 [3 7 1 6]
 [3 4 5 4]
 [8 1 3 7]
 [1 5 7 1]
 [9 7 2 9]
 [1 5 2 6]
 [4 5 6 6]
 [7 7 4 3]
 [4 7 8 5]
 [5 6 4 6]]

x_test:
[[3 7 5 8]
 [3 4 3 7]
 [6 1 1 6]
 [1 4 8 7]
 [7 2 5 7]
 [3 5 1 9]
 [5 4 8 4]
 [2 5 4 9]]

y_train:
[4 6 9 2 3 1 5 6 1 5 2 1]

y_test:
[7 5 5 9 6 5 7 9]
